import { Validators } from "@angular/forms";
import { FormData, FormDataRelations } from "src/app/interfaces/formData";

export const formData:FormData = {
  loggin:[
    {
      label:'Email',
      name:'email',
      type:'email',
      placeholder:'Email',
      validators: [Validators.required, Validators.email],
      minlength: 'El minimo de caracteres son 10',
      email: 'No es un email',
      disabled: false,
      default:''
    },
    {
      label:'Password',
      name:'password',
      type:'password',
      placeholder:'Password',
      validators: [Validators.required, Validators.minLength(8), Validators.maxLength(15)],
      minlength:'El minimo de caracteres son 8',
      maxlength:'El maximo de caracteres son 15',
      disabled: false,
      default:'',
    }
  ],
  egress:[
    {
      label:'Product Name',
      name:'name_product',
      type:'text',
      placeholder:'Product Name',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Quantity',
      name:'quantity',
      type:'number',
      placeholder:'Quantity',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Unit Price',
      name:'unit_price',
      type:'number',
      placeholder:'Unit Price',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Iternal Code',
      name:'internal_code',
      type:'number',
      placeholder:'Iternal Code',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Provider',
      name:'provider',
      type:'button',
      placeholder:'Provider',
      validators: [],
      disabled: false,
      default:''
    },
    {
      label:'Payment Method',
      name:'payment_method',
      type:'button',
      placeholder:'Provider',
      validators: [],
      disabled: false,
      default:''
    },
  ],
  income:[
    {
      label:'Product Name',
      name:'product',
      type:'text',
      placeholder:'Product Name',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Sales Quantity',
      name:'quantity_sold',
      type:'number',
      placeholder:'Sales Quantity',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'Price',
      name:'price',
      type:'number',
      placeholder:'Price',
      validators: [Validators.required],
      disabled: false,
      default:''
    },
    {
      label:'User name',
      name:'client',
      type:'button',
      placeholder:'User Name',
      validators: [],
      disabled: false,
      default:''
    },
    {
      label:'Payment method',
      name:'payment_method',
      type:'button',
      placeholder:'Payment Method',
      validators: [],
      disabled: false,
      default:''
    },
  ]
}
export const formDataRelations:FormDataRelations = {
  provider:[
    {
      label:'Provider Name',
      name:'name',
      placeholder:'Provider Name',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Business Name',
      name:'business_name',
      placeholder:'Business Name',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Business Name',
      name:'business_name',
      placeholder:'Business Name',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'RFC',
      name:'rfc',
      placeholder:'RFC',
      type:'text',
      validators: [Validators.minLength(14),Validators.maxLength(14)],
      minlength:'El minimo de caracteres son 14',
      maxlength:'El maximo de caracteres son 14',
      disabled: false,
      default:'',
    },
    {
      label:'Registration Date',
      name:'registration_date',
      placeholder:'Registration Date',
      type:'date',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Street',
      name:'street',
      placeholder:'Street',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Number',
      name:'number',
      placeholder:'Number',
      type:'number',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Neighborhood',
      name:'neighborhood',
      placeholder:'Neighborhood',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Postal Code',
      name:'postal_code',
      placeholder:'Postal Code',
      type:'number',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Municipality',
      name:'municipality',
      placeholder:'Municipality',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'City',
      name:'city',
      placeholder:'City',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Coutry',
      name:'country',
      placeholder:'Country',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Schedule visit',
      name:'schedule_visit',
      placeholder:'Schedule visit',
      type:'date',
      validators: [],
      disabled: false,
      default:'',
    },
    {
      label:'Status',
      name:'status',
      placeholder:'Status',
      type:'text',
      validators: [],
      disabled: false,
      default:'',
    },

  ],
  payment_method:[
    {
      label: 'Card Number',
      name: 'card_number',
      placeholder: 'Card Number',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Expiration Month',
      name: 'month',
      placeholder: 'Expiration Month',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Expiration Year',
      name: 'year',
      placeholder: 'Expiration Year',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'CVC',
      name: 'cvc',
      placeholder: 'CVC',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Card Holder',
      name: 'holder',
      placeholder: 'Card Holder',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Folio',
      name: 'folio',
      placeholder: 'Folio',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Issue Date',
      name: 'issue_date',
      placeholder: 'Issue Date',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Entry Date',
      name: 'entry_date',
      placeholder: 'Entry Date',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Description',
      name: 'description',
      placeholder: 'Description',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Reference',
      name: 'reference',
      placeholder: 'Reference',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Type',
      name: 'type',
      placeholder: 'Type',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
  ],
  client:[
    {
      label: 'Full Name',
      name: 'name',
      placeholder: 'Full Name',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Last Name',
      name: 'last_name',
      placeholder: 'Last Name',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Middle Name',
      name: 'middle_name',
      placeholder: 'Middle Name',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Birthdate',
      name: 'birthdate',
      placeholder: 'Birthdate',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Gender',
      name: 'gender',
      placeholder: 'Gender',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Registration Date',
      name: 'registration_date',
      placeholder: 'Registration Date',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Activation Date',
      name: 'activation_date',
      placeholder: 'Activation Date',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'RFC',
      name: 'rfc',
      placeholder: 'RFC',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'CURP',
      name: 'curp',
      placeholder: 'CURP',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'NSS',
      name: 'nss',
      placeholder: 'NSS',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Cell Phone',
      name: 'cell_phone',
      placeholder: 'Cell Phone',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Email',
      name: 'email',
      placeholder: 'Email',
      type: 'email',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Password',
      name: 'password',
      placeholder: 'Password',
      type: 'password',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Blood Type',
      name: 'blood_type',
      placeholder: 'Blood Type',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'License',
      name: 'license',
      placeholder: 'License',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Ailments',
      name: 'ailments',
      placeholder: 'Ailments',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Nationality',
      name: 'nationality',
      placeholder: 'Nationality',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Street',
      name: 'street',
      placeholder: 'Street',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Number',
      name: 'number',
      placeholder: 'Residence Number',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Neighborhood',
      name: 'neighborhood',
      placeholder: 'Neighborhood',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Postal Code',
      name: 'postal_code',
      placeholder: 'Postal Code',
      type: 'number',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Municipality',
      name: 'municipality',
      placeholder: 'Municipality',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'City',
      name: 'city',
      placeholder: 'City',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Country',
      name: 'country',
      placeholder: 'Country',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Address Reference',
      name: 'address_reference',
      placeholder: 'Address Reference',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Additional Comment',
      name: 'comment',
      placeholder: 'Additional Comment',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Last Login Date',
      name: 'last_login',
      placeholder: 'Last Login Date',
      type: 'date',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'User Status',
      name: 'status',
      placeholder: 'User Status',
      type: 'text',
      validators: [],
      disabled: false,
      default: '',
    },
    {
      label: 'Confirmation',
      name: 'confirmation',
      placeholder: 'Confirm User',
      type: 'checkbox',
      validators: [],
      disabled: false,
      default: false,
    },
    // {
    //   label: 'Role',
    //   name: 'role',
    //   placeholder: 'Select User Role',
    //   type: 'text',
    //   validators: [],
    //   disabled: false,
    //   default: '',
    // },
  ],
}
