import { Export } from "../interface/export";

export const data:Export = {
  cart:{
    fields:[
      {label:'Amount', value:'amount'},
      {label:'Product Name', value:'products'},
      {label:'User Name', value:'custom_user'},
      {label:'Sale Amount', value:'sale'},
    ],
  },
  credit:{
    fields:[
      {label:'Limit',value:'limit'},
      {label:'Start Date',value:'start_date'},
      {label:'End Date',value:'end_date'},
      {label:'Validity',value:'validity'},
      {label:'Interests',value:'interests'},
      {label:'Status',value:'status'},
      {label:'Payments Amount',value:'payments'},
      {label:'Payment Method Card Number',value:'payment_method'},
      {label:'User Name', value:'custom_user'},
    ],
  },
  dimension:{
    fields:[
      {label:'Name',value:'name'},
      {label:'Width',value:'width'},
      {label:'Height',value:'height' },
      {label:'Long',value:'long'},
      {label:'Products Name', value:'products'}
    ],
  },
  egress:{
    fields:[
      {label:'Name Product',value:'name_product'},
      {label:'Quantity',value:'quantity'},
      {label:'Unit Price',value:'unit_price'},
      {label:'Total Egress',value:'total_egress'},
      {label:'Date',value:'date'},
      {label:'Provider Name',value:'provider'
      },
      {label:'Payment Method Card Number',value:'payment_method'}
    ],
  },
  expense:{
    fields:[
      {label:'Description',value:'description'},
      {label:'Date',value:'date'},
      {label:'Amount',value:'amount'},
      {label:'Category',value:'category' },
      {label:'Status',value:'status'},
      {label:'Trucks Serial Number',value:'trucks'},
      {label:'User Name',value:'custom_user'}
    ],
  },
  history:{
    fields: [
      { label: 'Date', value: 'date' },
      { label: 'Start Time', value: 'start_time' },
      { label: 'End Time', value: 'end_time' },
      { label: 'Status', value: 'status' },
      { label: 'User Name', value: 'custom_user' },
      { label: 'Truck Serial Number', value: 'truck' },
    ],
  },
  income:{
    fields: [
      { label: 'Product Name', value: 'product' },
      { label: 'Quantity Sold', value: 'quantity_sold' },
      { label: 'Price', value: 'price' },
      { label: 'Total Income', value: 'total_income' },
      { label: 'Date', value: 'date' },
      { label: 'User Name', value: 'client' },
      { label: 'Payment Method Card Number', value: 'payment_method' },
    ],
  },
  lot:{
    fields: [
      { label: 'Internal Code', value: 'internal_code' },
      { label: 'Arrival Date', value: 'arrival_date' },
      { label: 'Expiration Date', value: 'expiration_date' },
      { label: 'Acquisition Date', value: 'acquisition_date' },
      { label: 'Cost', value: 'cost' },
      { label: 'Purchases Cost', value: 'purchases' },
      { label: 'Products Name', value: 'products' },
    ],
  },
  payment:{
    fields: [
      { label: 'Amount', value: 'amount' },
      { label: 'Date', value: 'date' },
      { label: 'Status', value: 'status' },
      { label: 'Credit Start Date', value: 'credit' },
      { label: 'User Name', value: 'custom_user' },
    ],
  },
  payment_method:{
    fields: [
      { label: 'Card Number', value: 'card_number' },
      { label: 'Month', value: 'month' },
      { label: 'Year', value: 'year' },
      { label: 'CVC', value: 'cvc' },
      { label: 'Holder', value: 'holder' },
      { label: 'Folio', value: 'folio' },
      { label: 'Issue Date', value: 'issue_date' },
      { label: 'Entry Date', value: 'entry_date' },
      { label: 'Description', value: 'description' },
      { label: 'Reference', value: 'reference' },
      { label: 'Type', value: 'type' },
      { label: 'Credits Start Date', value: 'credits' },
      { label: 'Purchases Cost', value: 'purchases' },
      { label: 'User Name', value: 'custom_user' },
      { label: 'Sales Amount', value: 'sales' },
      { label: 'Egress Product Name', value: 'egress' },
      { label: 'Income Product', value: 'income' },
    ],
  },
  premise:{
    fields: [
      { label: 'Name', value: 'name' },
      { label: 'Alias', value: 'alias' },
      { label: 'Business Name', value: 'business_name' },
      { label: 'RFC', value: 'rfc' },
      { label: 'Start Date', value: 'start_date' },
      { label: 'Street', value: 'street' },
      { label: 'Neighborhood', value: 'neighborhood' },
      { label: 'Exterior Number', value: 'exterior_number' },
      { label: 'Municipality', value: 'municipality' },
      { label: 'Interior Number', value: 'interior_number' },
      { label: 'City', value: 'city' },
      { label: 'Postal Code', value: 'postal_code' },
      { label: 'Latitude', value: 'latitude' },
      { label: 'Longitude', value: 'longitude' },
      { label: 'Phone', value: 'phone' },
      { label: 'Cell Phone', value: 'cell_phone' },
      { label: 'Business Type', value: 'business_type' },
      { label: 'Status', value: 'status' },
      { label: 'User Name', value: 'custom_users' },
      { label: 'Sales Amount', value: 'sales' },
    ],
  },
  product:{
    fields: [
      { label: 'Name', value: 'name' },
      { label: 'Net Weight', value: 'net_weight' },
      { label: 'Presentation', value: 'presentation' },
      { label: 'Brand', value: 'brand' },
      { label: 'Generic Description', value: 'generic_description' },
      { label: 'Price', value: 'price' },
      { label: 'Cost', value: 'cost' },
      { label: 'Available Inventory', value: 'available_inventory' },
      { label: 'Min Value', value: 'min_value' },
      { label: 'Barcode', value: 'barcode' },
      { label: 'Internal Code', value: 'internal_code' },
      { label: 'Status', value: 'status' },
      { label: 'Unit of Measure', value: 'unit_of_measure' },
      { label: 'Measurement', value: 'measurement' },
      { label: 'Carts', value: 'carts' },
      { label: 'Dimension', value: 'dimension' },
      { label: 'Lots', value: 'lots' },
      { label: 'Promotions', value: 'promotions' },
      { label: 'Provider', value: 'provider' },
    ],
  },
  promotion:{
    fields: [
      { label: 'Creation Date', value: 'creation_date' },
      { label: 'Expiration Date', value: 'expiration_date' },
      { label: 'Discount Value', value: 'discount_value' },
      { label: 'Reference Code', value: 'reference_code' },
      { label: 'Condition', value: 'condition' },
      { label: 'Product Name', value: 'products' },
    ],
  },
  provider:{
    fields: [
      { label: 'Name', value: 'name' },
      { label: 'Business Name', value: 'business_name' },
      { label: 'RFC', value: 'rfc' },
      { label: 'Registration Date', value: 'registration_date' },
      { label: 'Street', value: 'street' },
      { label: 'Number', value: 'number' },
      { label: 'Neighborhood', value: 'neighborhood' },
      { label: 'Postal Code', value: 'postal_code' },
      { label: 'Municipality', value: 'municipality' },
      { label: 'City', value: 'city' },
      { label: 'Country', value: 'country' },
      { label: 'Scheduled Visit', value: 'scheduled_visit' },
      { label: 'Status', value: 'status' },
      { label: 'Products Name', value: 'products' },
      { label: 'Purchases Cost', value: 'purchases' },
      { label: 'Egresses Name Product', value: 'egresses' },
    ],
  },
  purchase:{
    fields: [
      { label: 'Cost', value: 'cost' },
      { label: 'Order Date', value: 'order_date' },
      { label: 'Reference', value: 'reference' },
      { label: 'Arrival Date', value: 'arrival_date' },
      { label: 'Status', value: 'status' },
      { label: 'Lot', value: 'lot' },
      { label: 'Payment Method Card Number', value: 'payment_method' },
      { label: 'Provider Name', value: 'provider' },
      { label: 'Users Name', value: 'custom_users' },
    ],
  },
  role:{
    fields: [
      { label: 'Role', value: 'role' },
      { label: 'Users', value: 'users' },
    ],
  },
  route:{
    fields: [
      { label: 'Description', value: 'description' },
      { label: 'Origin', value: 'origin' },
      { label: 'Destination', value: 'destination' },
      { label: 'Departure Date', value: 'departure_date' },
      { label: 'Arrival Date', value: 'arrival_date' },
      { label: 'Reference', value: 'reference' },
      { label: 'Received Goods Name', value: 'received_goods_name' },
      { label: 'Comments', value: 'comments' },
      { label: 'Status', value: 'status' },
      { label: 'Cyclic Route', value: 'cyclic_route' },
      { label: 'Trucks Serial Number', value: 'trucks' },
      { label: 'Sales Amount', value: 'sales' },
    ],
  },
  sale:{
    fields: [
      { label: 'Amount', value: 'amount' },
      { label: 'Total Amount', value: 'total_amount' },
      { label: 'Date', value: 'date' },
      { label: 'Invoice', value: 'invoice' },
      { label: 'Classification', value: 'classification' },
      { label: 'Delivery Date', value: 'delivery_date' },
      { label: 'Pending Delivery', value: 'pending_delivery' },
      { label: 'Paid', value: 'paid' },
      { label: 'Status', value: 'status' },
      { label: 'Carts Amount', value: 'carts' },
      { label: 'Premise Name', value: 'premise' },
      { label: 'Payment Methods Card Number', value: 'payment_methods' },
      { label: 'Routes Description', value: 'routes' },
      { label: 'User Name', value: 'custom_user' },
      { label: 'Sellers Name', value: 'sellers' },
    ],
  },
  seller:{
    fields: [
      { label: 'Name', value: 'name' },
      { label: 'Sales', value: 'sales' },
    ],
  },
  truck:{
    fields: [
      // { label: 'Plate Details', value: 'plate_details' },
      { label: 'Serial Number', value: 'serial_number' },
      { label: 'VIN', value: 'vin' },
      { label: 'Expenses', value: 'expenses' },
      { label: 'Histories', value: 'histories' },
      { label: 'Routes Description', value: 'routes' },
      { label: 'User Name', value: 'custom_user' },
    ],
  },
  user:{
    fields: [
      { label: 'Name', value: 'name' },
      { label: 'Last Name', value: 'last_name' },
      { label: 'Middle Name', value: 'middle_name' },
      { label: 'Birthdate', value: 'birthdate' },
      { label: 'Gender', value: 'gender' },
      { label: 'Registration Date', value: 'registration_date' },
      { label: 'Activation Date', value: 'activation_date' },
      { label: 'RFC', value: 'rfc' },
      { label: 'CURP', value: 'curp' },
      { label: 'NSS', value: 'nss' },
      { label: 'Cell Phone', value: 'cell_phone' },
      { label: 'Email', value: 'email' },
      { label: 'Password', value: 'password' },
      { label: 'Blood Type', value: 'blood_type' },
      { label: 'License', value: 'license' },
      { label: 'Allergies', value: 'allergies' },
      { label: 'Ailments', value: 'ailments' },
      { label: 'Nationality', value: 'nationality' },
      { label: 'Street', value: 'street' },
      { label: 'Number', value: 'number' },
      { label: 'Neighborhood', value: 'neighborhood' },
      { label: 'Postal Code', value: 'postal_code' },
      { label: 'Municipality', value: 'municipality' },
      { label: 'City', value: 'city' },
      { label: 'Country', value: 'country' },
      { label: 'Address Reference', value: 'address_reference' },
      { label: 'Comment', value: 'comment' },
      { label: 'Last Logging', value: 'last_loggin' },
      { label: 'Status', value: 'status' },
      { label: 'Confirmation', value: 'confirmation' },
      { label: 'Role', value: 'role' },
      { label: 'Payments', value: 'payments' },
      { label: 'Carts', value: 'carts' },
      { label: 'Credits', value: 'credits' },
      { label: 'Expenses', value: 'expenses' },
      { label: 'Histories', value: 'histories' },
      { label: 'Premises', value: 'premises' },
      { label: 'Payment Methods', value: 'payment_methods' },
      { label: 'Purchases', value: 'purchases' },
      { label: 'Sales', value: 'sales' },
      { label: 'Trucks', value: 'trucks' },
      { label: 'Income', value: 'income' },
    ],
  },
}
